# Generated by Django 5.2.3 on 2025-06-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_attendance_date_remove_attendance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='score',
            new_name='marks_obtained',
        ),
    ]
